version: "3.9"
services:
  ubuntu1:
    build: .
    image: ubuntu:latest
    container_name: ubuntu_container01
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ./data1:/data
      - ./vpn1.py:/vpn/vpn.py
      - ./sniffer.py:/vpn/sniffer.py
    networks:
      network-c:
        ipv4_address: 192.168.10.100

  ubuntu2:
    build: .
    image: ubuntu:latest
    container_name: ubuntu_container02
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ./data2:/data
      - ./vpn2.py:/vpn/vpn.py
    networks:
      network-c:
        ipv4_address: 192.168.10.101

networks:
   network-a:
     driver: bridge
     ipam: 
       config:
         - subnet: 10.10.1.0/24

   network-b:
     driver: bridge
     ipam: 
       config:
         - subnet: 10.10.2.0/24
  
   network-c:
     driver: bridge
     ipam: 
       config:
         - subnet: 192.168.10.0/24




